/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PlayingRole = IDL.Variant({
  'allRounder' : IDL.Null,
  'bowler' : IDL.Null,
  'wicketKeeper' : IDL.Null,
  'batsman' : IDL.Null,
});
export const BattingSkill = IDL.Variant({
  'novice' : IDL.Null,
  'internationalStar' : IDL.Null,
  'national' : IDL.Null,
  'amateur' : IDL.Null,
  'worldClass' : IDL.Null,
});
export const BowlingSkill = IDL.Variant({
  'novice' : IDL.Null,
  'internationalStar' : IDL.Null,
  'national' : IDL.Null,
  'amateur' : IDL.Null,
  'worldClass' : IDL.Null,
});
export const FieldingSkill = IDL.Variant({
  'learning' : IDL.Null,
  'goldGlove' : IDL.Null,
  'average' : IDL.Null,
  'reliable' : IDL.Null,
});
export const Player = IDL.Record({
  'id' : IDL.Nat,
  'bowlingSkill' : BowlingSkill,
  'playingRole' : PlayingRole,
  'name' : IDL.Text,
  'battingSkill' : BattingSkill,
  'team' : IDL.Text,
  'fieldingSkill' : FieldingSkill,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FantasyTeam = IDL.Record({
  'playerIds' : IDL.Vec(IDL.Nat),
  'viceCaptainId' : IDL.Nat,
  'teamId' : IDL.Nat,
  'captainId' : IDL.Nat,
});
export const TeamEntry = IDL.Record({
  'userId' : IDL.Principal,
  'team' : FantasyTeam,
});
export const Contest = IDL.Record({
  'isFinished' : IDL.Bool,
  'participants' : IDL.Vec(TeamEntry),
  'contestId' : IDL.Nat,
  'entryLimit' : IDL.Opt(IDL.Nat),
  'matchId' : IDL.Nat,
  'prizePool' : IDL.Nat,
});
export const Match = IDL.Record({
  'id' : IDL.Nat,
  'team1' : IDL.Text,
  'team2' : IDL.Text,
  'isFinished' : IDL.Bool,
  'venue' : IDL.Text,
  'date' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'avatar' : IDL.Text,
});
export const LeaderboardEntry = IDL.Record({
  'userId' : IDL.Principal,
  'rank' : IDL.Nat,
  'totalPoints' : IDL.Nat,
  'teamId' : IDL.Nat,
});
export const TeamSelectionInput = IDL.Record({
  'playerIds' : IDL.Vec(IDL.Nat),
  'viceCaptainId' : IDL.Nat,
  'captainId' : IDL.Nat,
});
export const PlayerWithPoints = IDL.Record({
  'playerId' : IDL.Nat,
  'points' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPlayer' : IDL.Func(
      [
        IDL.Text,
        PlayingRole,
        BattingSkill,
        BowlingSkill,
        FieldingSkill,
        IDL.Text,
      ],
      [Player],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createContestForMatch' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Opt(IDL.Nat)],
      [Contest],
      [],
    ),
  'createMatch' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Match],
      [],
    ),
  'finishMatch' : IDL.Func([IDL.Nat], [], []),
  'getAllMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
  'getAllPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContest' : IDL.Func([IDL.Nat], [IDL.Opt(Contest)], ['query']),
  'getContestLeaderboard' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(LeaderboardEntry)],
      ['query'],
    ),
  'getContestsForMatch' : IDL.Func([IDL.Nat], [IDL.Vec(Contest)], ['query']),
  'getMatch' : IDL.Func([IDL.Nat], [IDL.Opt(Match)], ['query']),
  'getMyContests' : IDL.Func([], [IDL.Vec(Contest)], ['query']),
  'getMyTeams' : IDL.Func([], [IDL.Vec(FantasyTeam)], ['query']),
  'getPlayer' : IDL.Func([IDL.Nat], [IDL.Opt(Player)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinContest' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'selectTeamWithValidation' : IDL.Func(
      [IDL.Nat, TeamSelectionInput],
      [FantasyTeam],
      [],
    ),
  'submitMatchPoints' : IDL.Func([IDL.Nat, IDL.Vec(PlayerWithPoints)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PlayingRole = IDL.Variant({
    'allRounder' : IDL.Null,
    'bowler' : IDL.Null,
    'wicketKeeper' : IDL.Null,
    'batsman' : IDL.Null,
  });
  const BattingSkill = IDL.Variant({
    'novice' : IDL.Null,
    'internationalStar' : IDL.Null,
    'national' : IDL.Null,
    'amateur' : IDL.Null,
    'worldClass' : IDL.Null,
  });
  const BowlingSkill = IDL.Variant({
    'novice' : IDL.Null,
    'internationalStar' : IDL.Null,
    'national' : IDL.Null,
    'amateur' : IDL.Null,
    'worldClass' : IDL.Null,
  });
  const FieldingSkill = IDL.Variant({
    'learning' : IDL.Null,
    'goldGlove' : IDL.Null,
    'average' : IDL.Null,
    'reliable' : IDL.Null,
  });
  const Player = IDL.Record({
    'id' : IDL.Nat,
    'bowlingSkill' : BowlingSkill,
    'playingRole' : PlayingRole,
    'name' : IDL.Text,
    'battingSkill' : BattingSkill,
    'team' : IDL.Text,
    'fieldingSkill' : FieldingSkill,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FantasyTeam = IDL.Record({
    'playerIds' : IDL.Vec(IDL.Nat),
    'viceCaptainId' : IDL.Nat,
    'teamId' : IDL.Nat,
    'captainId' : IDL.Nat,
  });
  const TeamEntry = IDL.Record({
    'userId' : IDL.Principal,
    'team' : FantasyTeam,
  });
  const Contest = IDL.Record({
    'isFinished' : IDL.Bool,
    'participants' : IDL.Vec(TeamEntry),
    'contestId' : IDL.Nat,
    'entryLimit' : IDL.Opt(IDL.Nat),
    'matchId' : IDL.Nat,
    'prizePool' : IDL.Nat,
  });
  const Match = IDL.Record({
    'id' : IDL.Nat,
    'team1' : IDL.Text,
    'team2' : IDL.Text,
    'isFinished' : IDL.Bool,
    'venue' : IDL.Text,
    'date' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'avatar' : IDL.Text });
  const LeaderboardEntry = IDL.Record({
    'userId' : IDL.Principal,
    'rank' : IDL.Nat,
    'totalPoints' : IDL.Nat,
    'teamId' : IDL.Nat,
  });
  const TeamSelectionInput = IDL.Record({
    'playerIds' : IDL.Vec(IDL.Nat),
    'viceCaptainId' : IDL.Nat,
    'captainId' : IDL.Nat,
  });
  const PlayerWithPoints = IDL.Record({
    'playerId' : IDL.Nat,
    'points' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPlayer' : IDL.Func(
        [
          IDL.Text,
          PlayingRole,
          BattingSkill,
          BowlingSkill,
          FieldingSkill,
          IDL.Text,
        ],
        [Player],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createContestForMatch' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Opt(IDL.Nat)],
        [Contest],
        [],
      ),
    'createMatch' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Match],
        [],
      ),
    'finishMatch' : IDL.Func([IDL.Nat], [], []),
    'getAllMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
    'getAllPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContest' : IDL.Func([IDL.Nat], [IDL.Opt(Contest)], ['query']),
    'getContestLeaderboard' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'getContestsForMatch' : IDL.Func([IDL.Nat], [IDL.Vec(Contest)], ['query']),
    'getMatch' : IDL.Func([IDL.Nat], [IDL.Opt(Match)], ['query']),
    'getMyContests' : IDL.Func([], [IDL.Vec(Contest)], ['query']),
    'getMyTeams' : IDL.Func([], [IDL.Vec(FantasyTeam)], ['query']),
    'getPlayer' : IDL.Func([IDL.Nat], [IDL.Opt(Player)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinContest' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'selectTeamWithValidation' : IDL.Func(
        [IDL.Nat, TeamSelectionInput],
        [FantasyTeam],
        [],
      ),
    'submitMatchPoints' : IDL.Func(
        [IDL.Nat, IDL.Vec(PlayerWithPoints)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };