/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BattingSkill = { 'novice' : null } |
  { 'internationalStar' : null } |
  { 'national' : null } |
  { 'amateur' : null } |
  { 'worldClass' : null };
export type BowlingSkill = { 'novice' : null } |
  { 'internationalStar' : null } |
  { 'national' : null } |
  { 'amateur' : null } |
  { 'worldClass' : null };
export interface Contest {
  'isFinished' : boolean,
  'participants' : Array<TeamEntry>,
  'contestId' : bigint,
  'entryLimit' : [] | [bigint],
  'matchId' : bigint,
  'prizePool' : bigint,
}
export interface FantasyTeam {
  'playerIds' : Array<bigint>,
  'viceCaptainId' : bigint,
  'teamId' : bigint,
  'captainId' : bigint,
}
export type FieldingSkill = { 'learning' : null } |
  { 'goldGlove' : null } |
  { 'average' : null } |
  { 'reliable' : null };
export interface LeaderboardEntry {
  'userId' : Principal,
  'rank' : bigint,
  'totalPoints' : bigint,
  'teamId' : bigint,
}
export interface Match {
  'id' : bigint,
  'team1' : string,
  'team2' : string,
  'isFinished' : boolean,
  'venue' : string,
  'date' : string,
}
export interface Player {
  'id' : bigint,
  'bowlingSkill' : BowlingSkill,
  'playingRole' : PlayingRole,
  'name' : string,
  'battingSkill' : BattingSkill,
  'team' : string,
  'fieldingSkill' : FieldingSkill,
}
export interface PlayerWithPoints { 'playerId' : bigint, 'points' : bigint }
export type PlayingRole = { 'allRounder' : null } |
  { 'bowler' : null } |
  { 'wicketKeeper' : null } |
  { 'batsman' : null };
export interface TeamEntry { 'userId' : Principal, 'team' : FantasyTeam }
export interface TeamSelectionInput {
  'playerIds' : Array<bigint>,
  'viceCaptainId' : bigint,
  'captainId' : bigint,
}
export interface UserProfile { 'name' : string, 'avatar' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPlayer' : ActorMethod<
    [string, PlayingRole, BattingSkill, BowlingSkill, FieldingSkill, string],
    Player
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createContestForMatch' : ActorMethod<
    [bigint, bigint, [] | [bigint]],
    Contest
  >,
  'createMatch' : ActorMethod<[string, string, string, string], Match>,
  'finishMatch' : ActorMethod<[bigint], undefined>,
  'getAllMatches' : ActorMethod<[], Array<Match>>,
  'getAllPlayers' : ActorMethod<[], Array<Player>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContest' : ActorMethod<[bigint], [] | [Contest]>,
  'getContestLeaderboard' : ActorMethod<[bigint], Array<LeaderboardEntry>>,
  'getContestsForMatch' : ActorMethod<[bigint], Array<Contest>>,
  'getMatch' : ActorMethod<[bigint], [] | [Match]>,
  'getMyContests' : ActorMethod<[], Array<Contest>>,
  'getMyTeams' : ActorMethod<[], Array<FantasyTeam>>,
  'getPlayer' : ActorMethod<[bigint], [] | [Player]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinContest' : ActorMethod<[bigint, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'selectTeamWithValidation' : ActorMethod<
    [bigint, TeamSelectionInput],
    FantasyTeam
  >,
  'submitMatchPoints' : ActorMethod<
    [bigint, Array<PlayerWithPoints>],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];