/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Player {
    id: bigint;
    bowlingSkill: BowlingSkill;
    playingRole: PlayingRole;
    name: string;
    battingSkill: BattingSkill;
    team: string;
    fieldingSkill: FieldingSkill;
}
export interface LeaderboardEntry {
    userId: Principal;
    rank: bigint;
    totalPoints: bigint;
    teamId: bigint;
}
export interface TeamEntry {
    userId: Principal;
    team: FantasyTeam;
}
export interface PlayerWithPoints {
    playerId: bigint;
    points: bigint;
}
export interface FantasyTeam {
    playerIds: Array<bigint>;
    viceCaptainId: bigint;
    teamId: bigint;
    captainId: bigint;
}
export interface Match {
    id: bigint;
    team1: string;
    team2: string;
    isFinished: boolean;
    venue: string;
    date: string;
}
export interface Contest {
    isFinished: boolean;
    participants: Array<TeamEntry>;
    contestId: bigint;
    entryLimit?: bigint;
    matchId: bigint;
    prizePool: bigint;
}
export interface TeamSelectionInput {
    playerIds: Array<bigint>;
    viceCaptainId: bigint;
    captainId: bigint;
}
export interface UserProfile {
    name: string;
    avatar: string;
}
export enum BattingSkill {
    novice = "novice",
    internationalStar = "internationalStar",
    national = "national",
    amateur = "amateur",
    worldClass = "worldClass"
}
export enum FieldingSkill {
    learning = "learning",
    goldGlove = "goldGlove",
    average = "average",
    reliable = "reliable"
}
export enum PlayingRole {
    allRounder = "allRounder",
    bowler = "bowler",
    wicketKeeper = "wicketKeeper",
    batsman = "batsman"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addPlayer(name: string, playingRole: PlayingRole, battingSkill: BattingSkill, bowlingSkill: BowlingSkill, fieldingSkill: FieldingSkill, team: string): Promise<Player>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createContestForMatch(matchId: bigint, prizePool: bigint, entryLimit: bigint | null): Promise<Contest>;
    createMatch(team1: string, team2: string, date: string, venue: string): Promise<Match>;
    finishMatch(matchId: bigint): Promise<void>;
    getAllMatches(): Promise<Array<Match>>;
    getAllPlayers(): Promise<Array<Player>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getContest(contestId: bigint): Promise<Contest | null>;
    getContestLeaderboard(contestId: bigint): Promise<Array<LeaderboardEntry>>;
    getContestsForMatch(matchId: bigint): Promise<Array<Contest>>;
    getMatch(matchId: bigint): Promise<Match | null>;
    getMyContests(): Promise<Array<Contest>>;
    getMyTeams(): Promise<Array<FantasyTeam>>;
    getPlayer(playerId: bigint): Promise<Player | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    joinContest(contestId: bigint, teamId: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    selectTeamWithValidation(matchId: bigint, selection: TeamSelectionInput): Promise<FantasyTeam>;
    submitMatchPoints(matchId: bigint, points: Array<PlayerWithPoints>): Promise<void>;
}
import type { BattingSkill as _BattingSkill, BowlingSkill as _BowlingSkill, Contest as _Contest, FieldingSkill as _FieldingSkill, Match as _Match, Player as _Player, PlayingRole as _PlayingRole, TeamEntry as _TeamEntry, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addPlayer(arg0: string, arg1: PlayingRole, arg2: BattingSkill, arg3: BowlingSkill, arg4: FieldingSkill, arg5: string): Promise<Player> {
        if (this.processError) {
            try {
                const result = await this.actor.addPlayer(arg0, to_candid_PlayingRole_n1(this._uploadFile, this._downloadFile, arg1), to_candid_BattingSkill_n3(this._uploadFile, this._downloadFile, arg2), to_candid_BowlingSkill_n5(this._uploadFile, this._downloadFile, arg3), to_candid_FieldingSkill_n6(this._uploadFile, this._downloadFile, arg4), arg5);
                return from_candid_Player_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPlayer(arg0, to_candid_PlayingRole_n1(this._uploadFile, this._downloadFile, arg1), to_candid_BattingSkill_n3(this._uploadFile, this._downloadFile, arg2), to_candid_BowlingSkill_n5(this._uploadFile, this._downloadFile, arg3), to_candid_FieldingSkill_n6(this._uploadFile, this._downloadFile, arg4), arg5);
            return from_candid_Player_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n17(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n17(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createContestForMatch(arg0: bigint, arg1: bigint, arg2: bigint | null): Promise<Contest> {
        if (this.processError) {
            try {
                const result = await this.actor.createContestForMatch(arg0, arg1, to_candid_opt_n19(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Contest_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createContestForMatch(arg0, arg1, to_candid_opt_n19(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Contest_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async createMatch(arg0: string, arg1: string, arg2: string, arg3: string): Promise<Match> {
        if (this.processError) {
            try {
                const result = await this.actor.createMatch(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMatch(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async finishMatch(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.finishMatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.finishMatch(arg0);
            return result;
        }
    }
    async getAllMatches(): Promise<Array<Match>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMatches();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMatches();
            return result;
        }
    }
    async getAllPlayers(): Promise<Array<Player>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPlayers();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPlayers();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContest(arg0: bigint): Promise<Contest | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getContest(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContest(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContestLeaderboard(arg0: bigint): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContestLeaderboard(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContestLeaderboard(arg0);
            return result;
        }
    }
    async getContestsForMatch(arg0: bigint): Promise<Array<Contest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContestsForMatch(arg0);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContestsForMatch(arg0);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMatch(arg0: bigint): Promise<Match | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatch(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatch(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyContests(): Promise<Array<Contest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyContests();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyContests();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyTeams(): Promise<Array<FantasyTeam>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyTeams();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyTeams();
            return result;
        }
    }
    async getPlayer(arg0: bigint): Promise<Player | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayer(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayer(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async joinContest(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.joinContest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinContest(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async selectTeamWithValidation(arg0: bigint, arg1: TeamSelectionInput): Promise<FantasyTeam> {
        if (this.processError) {
            try {
                const result = await this.actor.selectTeamWithValidation(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.selectTeamWithValidation(arg0, arg1);
            return result;
        }
    }
    async submitMatchPoints(arg0: bigint, arg1: Array<PlayerWithPoints>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitMatchPoints(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitMatchPoints(arg0, arg1);
            return result;
        }
    }
}
function from_candid_BattingSkill_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BattingSkill): BattingSkill {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_BowlingSkill_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BowlingSkill): BowlingSkill {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Contest_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Contest): Contest {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_FieldingSkill_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FieldingSkill): FieldingSkill {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Player_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Player): Player {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_PlayingRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlayingRole): PlayingRole {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Contest]): Contest | null {
    return value.length === 0 ? null : from_candid_Contest_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Match]): Match | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Player]): Player | null {
    return value.length === 0 ? null : from_candid_Player_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    isFinished: boolean;
    participants: Array<_TeamEntry>;
    contestId: bigint;
    entryLimit: [] | [bigint];
    matchId: bigint;
    prizePool: bigint;
}): {
    isFinished: boolean;
    participants: Array<TeamEntry>;
    contestId: bigint;
    entryLimit?: bigint;
    matchId: bigint;
    prizePool: bigint;
} {
    return {
        isFinished: value.isFinished,
        participants: value.participants,
        contestId: value.contestId,
        entryLimit: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.entryLimit)),
        matchId: value.matchId,
        prizePool: value.prizePool
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    bowlingSkill: _BowlingSkill;
    playingRole: _PlayingRole;
    name: string;
    battingSkill: _BattingSkill;
    team: string;
    fieldingSkill: _FieldingSkill;
}): {
    id: bigint;
    bowlingSkill: BowlingSkill;
    playingRole: PlayingRole;
    name: string;
    battingSkill: BattingSkill;
    team: string;
    fieldingSkill: FieldingSkill;
} {
    return {
        id: value.id,
        bowlingSkill: from_candid_BowlingSkill_n10(_uploadFile, _downloadFile, value.bowlingSkill),
        playingRole: from_candid_PlayingRole_n12(_uploadFile, _downloadFile, value.playingRole),
        name: value.name,
        battingSkill: from_candid_BattingSkill_n14(_uploadFile, _downloadFile, value.battingSkill),
        team: value.team,
        fieldingSkill: from_candid_FieldingSkill_n15(_uploadFile, _downloadFile, value.fieldingSkill)
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    novice: null;
} | {
    internationalStar: null;
} | {
    national: null;
} | {
    amateur: null;
} | {
    worldClass: null;
}): BattingSkill {
    return "novice" in value ? BattingSkill.novice : "internationalStar" in value ? BattingSkill.internationalStar : "national" in value ? BattingSkill.national : "amateur" in value ? BattingSkill.amateur : "worldClass" in value ? BattingSkill.worldClass : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    allRounder: null;
} | {
    bowler: null;
} | {
    wicketKeeper: null;
} | {
    batsman: null;
}): PlayingRole {
    return "allRounder" in value ? PlayingRole.allRounder : "bowler" in value ? PlayingRole.bowler : "wicketKeeper" in value ? PlayingRole.wicketKeeper : "batsman" in value ? PlayingRole.batsman : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    learning: null;
} | {
    goldGlove: null;
} | {
    average: null;
} | {
    reliable: null;
}): FieldingSkill {
    return "learning" in value ? FieldingSkill.learning : "goldGlove" in value ? FieldingSkill.goldGlove : "average" in value ? FieldingSkill.average : "reliable" in value ? FieldingSkill.reliable : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Player>): Array<Player> {
    return value.map((x)=>from_candid_Player_n8(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Contest>): Array<Contest> {
    return value.map((x)=>from_candid_Contest_n20(_uploadFile, _downloadFile, x));
}
function to_candid_BattingSkill_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BattingSkill): _BattingSkill {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_BowlingSkill_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BowlingSkill): _BowlingSkill {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_FieldingSkill_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FieldingSkill): _FieldingSkill {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_PlayingRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlayingRole): _PlayingRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlayingRole): {
    allRounder: null;
} | {
    bowler: null;
} | {
    wicketKeeper: null;
} | {
    batsman: null;
} {
    return value == PlayingRole.allRounder ? {
        allRounder: null
    } : value == PlayingRole.bowler ? {
        bowler: null
    } : value == PlayingRole.wicketKeeper ? {
        wicketKeeper: null
    } : value == PlayingRole.batsman ? {
        batsman: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BattingSkill): {
    novice: null;
} | {
    internationalStar: null;
} | {
    national: null;
} | {
    amateur: null;
} | {
    worldClass: null;
} {
    return value == BattingSkill.novice ? {
        novice: null
    } : value == BattingSkill.internationalStar ? {
        internationalStar: null
    } : value == BattingSkill.national ? {
        national: null
    } : value == BattingSkill.amateur ? {
        amateur: null
    } : value == BattingSkill.worldClass ? {
        worldClass: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FieldingSkill): {
    learning: null;
} | {
    goldGlove: null;
} | {
    average: null;
} | {
    reliable: null;
} {
    return value == FieldingSkill.learning ? {
        learning: null
    } : value == FieldingSkill.goldGlove ? {
        goldGlove: null
    } : value == FieldingSkill.average ? {
        average: null
    } : value == FieldingSkill.reliable ? {
        reliable: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
